# Generated by Django 5.0.1 on 2024-01-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuneTracker', '0002_alter_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
